name: Upload Website Demos to Spaces

on:
  workflow_dispatch:
  pull_request:
    types: closed
    branches:
      - main
jobs:
  upload-wheel-aws:
    if: github.event.pull_request.merged == true || github.event.action == ''
    name: Upload Demos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - name: Install pip
        run: python -m pip install build requests
      - name: Build Wheel
        run: |
          pnpm i --frozen-lockfile --ignore-scripts
          pnpm build
          python3 -m build -w
        env:
          NODE_OPTIONS: --max_old_space_size=8192
      - name: Upload Wheel to AWS
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.MAIN_BUILDS_KEY }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.MAIN_BUILDS_SECRET }}
          export AWS_DEFAULT_REGION=us-east-1
          export LATEST_COMMIT=$(git log -1 --format="%H")
          aws s3 cp dist/gradio-*-py3-none-any.whl s3://gradio-main-build/$LATEST_COMMIT/
      - name: Install Hub Client Library
        run: pip install huggingface-hub
      - name: Upload Demos to Spaces
        run: |
          export AUTH_TOKEN=${{ secrets.MAIN_BUILDS_SECRET }}
          export LATEST_COMMIT=$(git log -1 --format="%H")
          python scripts/upload_website_demos.py --WHEEL_URL https://gradio-main-build.s3.amazonaws.com/$LATEST_COMMIT/